version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"  # Exposes MongoDB to the host machine
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Exposes Redis to the host machine
    networks:
      - app_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
