name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
    actions: read
    contents: read

jobs:
    lint-and-build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 22
            cache: 'npm'
        - run: npm ci
  
        - uses: nrwl/nx-set-shas@v4
  
        - run: npx nx format:check
        - run: npx nx affected -t lint test build e2e-ci

        - name: Build UI
          run: npm run build:ui

        - name: Build API
          run: npm run build:api

        - name: Build libs
          run: npm run build:lib

        - name: Run Linting UI
          run: npm run lint:ui

        - name: Run Linting API
          run: npm run lint:ui

        - name: Run Linting UI:e2e
          run: npm run lint:e2e

        - name: Run Linting UI:e2e
          run: npm run lint:lib